experiment_name: vietnam-clouds
experiment_type: clouds

data_dir: /lscratch/jacaraba/vietnam-lcluc/clouds-categorical-notinclude
dataset_csv: /home/jacaraba/vietnam-lcluc/projects/vietnam_clouds/vietnam_clouds.csv

seed: 42
gpu_devices: 0,1,2,3
mixed_precision: False
xla: False

input_bands:
  - Blue
  - Green
  - Red
  - NIR1
  - HOM1
  - HOM2

output_bands:
  - Blue
  - Green
  - Red
  - NIR1

mean:
  - 1
std:
  - 1

tile_size: 256
include_classes: False
augment: True
standardize: True
batch_size: 128
n_classes: 2
test_size: 0.20
learning_rate: 0.0001
max_epochs: 6000
#loss: tversky
loss: categorical_crossentropy

window_size: 8192
inference_overlap: 2
inference_treshold: 0.50

# this model had include_classes set to true
model_filename: /lscratch/jacaraba/vietnam-lcluc/clouds-categorical-notinclude/model/77-0.03.hdf5
inference_regex: '/att/gpfsfs/briskfs01/ppl/mwooten3/Vietnam_LCLUC/TOA/M1BS/pansharpen_TamNongClip/WV02_20130125_M1BS_103001001DD53500-toa_pansharpen_clip.tif'
inference_save_dir: /adapt/nobackup/projects/ilab/projects/Vietnam/Jordan/VIETNAM_PRIORITY/cloud_mask_test_categorical_notinclude
