#-----------------------------------------------------------------------
# Configuration File for Vietnam Crop Mapping
#-----------------------------------------------------------------------
#experiment_name: '2021-08-11' - cloudnet with dice loss
# experiment_name: '2021-08-11b' - crossentropy better, not great
# experiment_name: '2021-08-11c' - normal std, looks decent
# experiment_name: '2021-08-11d' - contrast sucks, contrast stretch plus std
# experiment_name: '2021-08-11f' - resnet unet with categorical, std, rectified
# experiment_name: '2021-08-11g' - none of the losses from sm is good
# 512 tile size, catgeorical, std
# experiment_name: '2021-08-11h'
# rectified adam with warmup, best so far, std
# experiment_name: '2021-08-11e'
# experiment_name: '2021-08-11i' - better than e, best for now
# more tiles to work with
# experiment_name: '2021-08-11j' - looks promising, combination of stds
experiment_name: '2021-08-11i'

#-----------------------------------------------------------------------
# General Parameters
#-----------------------------------------------------------------------
data_csv: 'config/VietnamCropDataset.csv'
data_output_dir: '/lscratch/jacaraba/vietnam-lcluc/crop-mapping'

input_bands:
  - Blue
  - Green
  - Red
  - NIR
  - BAI
  - NDVI
  - NDWI
output_bands:
  - Blue
  - Green
  - Red
  - NIR
  - BAI
  - NDVI
  - NDWI

#-----------------------------------------------------------------------
# Model Parameters
#-----------------------------------------------------------------------
seed: 22
tile_size: 128
n_classes: 7
test_size: 0.20
batch_size: 16
max_epochs: 6000
initial_epoch: 0

#-----------------------------------------------------------------------
# System Acceleration Parameters
#-----------------------------------------------------------------------
cuda_devices: 0,1,2,3

#-----------------------------------------------------------------------
# System Acceleration Parameters
#-----------------------------------------------------------------------
# Tiles to process
# (ai-lcluc) [jacaraba@gpu021 data]$ ls /att/nobackup/mwooten3/Senegal_LCLUC/VHR/priority-tiles/
# Aki-tiles-ETZ  eCasamance_stereo  kassassa_M1BS-8band  Konrad-tiles
# model_filename: '/home/jacaraba/senegal-lcluc/projects/cloud-mask/data/2021-08-10c-18.h5'
# model_filename: '/home/jacaraba/vietnam-lcluc/projects/crop-mapping/data/2021-08-11e-17.h5'
model_filename: '/home/jacaraba/vietnam-lcluc/projects/crop-mapping/data/2021-08-11i-19.h5'
data_predict: '/att/gpfsfs/briskfs01/ppl/mwooten3/Vietnam_LCLUC/CNN/7-band/*.tif'
inference_output_dir: '/att/gpfsfs/atrepo01/ILAB/projects/Vietnam/Jordan/Vietnam_LCLUC/2021-08-11i'